const $=s=>document.querySelector(s);let books=[],token='',view='all',format='all',currentId='',audibleRows=[];
let arrangement={order:[],shelves:[],sort:'author'},arrangementLoaded=false;
let selectionMode=false,selected=new Set(),visibleIds=[],bulkBusy=false;
const statusNames={unknown:'Uavklart',reading:'Leser nå',finished:'Fullført',paused:'Delvis lest',want:'Vil lese'};
const mediumNames={unknown:'Format uavklart',paper:'Papir',ebook:'E-bok',audio:'Lydbok',mixed:'Flere formater'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=[['#31564d','#f1e7cf'],['#894c3e','#fff0d6'],['#d5b67c','#2e392c'],['#303c53','#eee9d5'],['#64705d','#fff4df'],['#633f4c','#f8e7d2']];
// Nattbordet viser bare det som faktisk leses nå. Delvis/pausede bøker
// beholdes i hovedsamlingen og kan åpnes der.
const isCurrent=b=>b.status==='reading';
const finishedThisYear=b=>hasFinishedInYear(b,2026);
function progress(b){if(b.status==='finished')return 'Fullført';if(b.progress==null)return b.status==='paused'?'Delvis lest':'Fremdrift ikke oppgitt';return `${b.progress}${b.progress_unit==='percent'?' %':b.progress_unit==='pages'?' sider':' minutter'} lest`;}
function cover(b){if(b.cover)return `<img class="cover" src="${esc(b.cover)}" alt="Omslag: ${esc(b.title)}" loading="lazy">`;let [bg,fg]=colors[[...b.author].reduce((a,c)=>a+c.charCodeAt(0),0)%colors.length];return `<div class="type-cover" style="--cover-bg:${bg};--cover-fg:${fg}" aria-label="Tittelkort, originalomslag mangler"><span class="tc-author">${esc(b.author)}</span><span class="tc-title">${esc(b.title==='Gymnaslærer Pedersens beretning om den store politiske vekkelse som har hjemsøkt vårt land'?'Gymnaslærer Pedersen':b.title)}</span><span class="tc-series">${esc(b.series?b.series+' · '+b.series_index:'BOKHYLLA')}</span></div>`;}
function formats(b){let a=new Set(Array.isArray(b.formats)?b.formats:[]);if(!a.size&&b.medium&&b.medium!=='unknown'&&b.medium!=='mixed')a.add(b.medium);for(const x of b.assets){if(x.role==='supplement')continue;if(['EPUB','PDF','MOBI','AZW3'].includes(x.format))a.add('ebook');else if(['MP3','M4B','M4A','AAC','AAX','AAXC'].includes(x.format))a.add('audio');}if(b.audible_owned)a.add('audio');return [...a];}
async function api(path,body){let r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Bokhylla-Token':token},body:JSON.stringify(body)});let data=await r.json();if(!r.ok)throw Error(data.error||'Noe gikk galt.');return data;}
let toastTimer;function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',5500);}
async function load(){let data=await api('/api/library');books=data.books;token=data.token;arrangement=data.arrangement||arrangement;if(!arrangementLoaded){$('#sort').value=arrangement.sort||'author';arrangementLoaded=true;}render();}
function render(){
 const complete=books.filter(finishedThisYear).length,current=books.filter(isCurrent).length;
 $('#finished-count').textContent=complete;$('#current-count').textContent=current;$('#collection-count').textContent=books.length;$('#total-nav').textContent=books.length;$('#reading-nav').textContent=current;$('#year-nav').textContent=complete;$('#unknown-nav').textContent=books.filter(b=>b.status==='unknown').length;
 const labels={all:['Bokhylla di','Historiene du har lest. Og de som venter.','Hele samlingen'],reading:['Mellom sidene','Bøkene du er i gang med, i ditt tempo.','Påbegynte og delvis leste'],year:['Et år i bøker','Fullført i 2026, inkludert anslåtte gjennomlyttinger fra Audible.','Lest i 2026'],unknown:['Historier som venter','Disse finnes i biblioteket. Vi vet ennå ikke om du har lest dem.','Uavklart lesestatus']};
 $('#page-title').innerHTML=labels[view][0]+'<span>.</span>';$('#page-description').textContent=labels[view][1];$('#shelf-heading').textContent=labels[view][2];$('#current-section').hidden=view!=='all';
 $('#current-books').innerHTML=books.filter(b=>b.status==='reading').map(b=>`<button class="current-card" data-book="${b.id}"><div class="current-cover">${cover(b)}</div><div class="current-info"><div class="mini-title">${esc(b.title)}</div><div class="mini-author">${esc(b.author)}</div>${b.progress!=null&&b.progress_unit==='percent'?`<div class="progress-track"><i style="width:${b.progress}%"></i></div>`:'<div style="height:12px"></div>'}<span class="progress-label">${esc(progress(b))}</span></div></button>`).join('');
 let query=$('#search').value.toLocaleLowerCase('nb');let filtered=books.filter(b=>(view==='all'||view==='reading'&&isCurrent(b)||view==='year'&&finishedThisYear(b)||view==='unknown'&&b.status==='unknown')&&(format==='all'||formats(b).includes(format))&&`${b.title} ${b.author} ${b.series} ${b.source}`.toLocaleLowerCase('nb').includes(query));
 renderLibraryWall(filtered);
 document.querySelectorAll('#current-books [data-book]').forEach(el=>el.onclick=()=>openBook(el.dataset.book));
 updateSelectionBar();
}
function options(values,current){return Object.entries(values).map(([v,t])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(t)}</option>`).join('');}
function openBook(id){
 let b=books.find(b=>b.id===id);currentId=id;
 $('#detail').innerHTML=`<div class="detail-top"><div class="detail-cover">${cover(b)}</div><div class="detail-heading"><div class="eyebrow">${esc(b.series||'FRA BOKHYLLA')}${b.series&&b.series_index!=null?' · '+b.series_index:''}</div><h2>${esc(b.title)}</h2><p>${esc(b.author)}</p><span class="badge ${b.status}">${esc(statusNames[b.status])}</span><p class="muted">${esc(b.provenance.join(' · '))}</p>${!b.cover?'<p class="muted">Tittelkort · originalomslag mangler</p>':''}</div></div>
 <form id="book-form" class="detail-form"><div class="form-grid"><label>Lesestatus<select name="status">${options(statusNames,b.status)}</select></label><label>Lest / lyttet i år<input name="year" type="number" min="1900" max="2100" value="${b.year||''}" placeholder="Ukjent"></label><label>Fremdrift<input name="progress" type="number" min="0" step="any" value="${b.progress??''}" placeholder="Ikke oppgitt"></label><label>Enhet<select name="progress_unit">${options({percent:'Prosent',pages:'Sider',minutes:'Minutter'},b.progress_unit)}</select></label><fieldset class="format-checks wide"><legend>Jeg har boka som</legend>${[["audio","Lydbok"],["ebook","E-bok"],["paper","Fysisk bok"]].map(([v,t])=>`<label><input type="checkbox" name="formats" value="${v}" ${formats(b).includes(v)?"checked":""}>${t}</label>`).join("")}</fieldset><label>Antall ganger<input name="read_count" type="number" min="1" max="999" step="1" value="${b.read_count||1}" aria-label="Antall ganger jeg har lest eller lyttet til boka"><span class="muted">Pluss én hver gang du leser eller lytter til boka på nytt.</span></label><label>Tjeneste / kilde<input name="source" value="${esc(b.source)}" placeholder="F.eks. Audible eller NRK Radio"></label><label>Fullført dato, hvis kjent<input name="finished_date" type="date" value="${esc(b.finished_date)}"></label><label>Språk<input name="language" value="${esc(b.language)}" placeholder="F.eks. norsk eller italiensk"></label><div class="wide checks"><label><input name="year_uncertain" type="checkbox" ${b.year_uncertain?'checked':''}>Årstallet er usikkert</label><label><input name="title_uncertain" type="checkbox" ${b.title_uncertain?'checked':''}>Tittelen må bekreftes</label></div><label>Sjanger<input name="genre" value="${esc(b.genre||'')}" list="genres" placeholder="Uavklart sjanger"><datalist id="genres"><option>Fantasy</option><option>Science fiction</option><option>Krim og spenning</option><option>Romaner</option><option>Sakprosa</option><option>Biografi</option><option>LitRPG</option></datalist></label><label>Min hylle<select name="user_shelf">${options({'':'Ikke plassert',...Object.fromEntries([...new Set([...arrangement.shelves,...books.map(x=>x.user_shelf).filter(Boolean)])].map(x=>[x,x]))},b.user_shelf||'')}</select></label><label>Serie<input name="series" value="${esc(b.series||'')}"></label><label>Nummer i serien<input name="series_index" type="number" step="any" min="0" value="${b.series_index??''}"></label><div class="wide manual-move"><button type="button" id="move-earlier" class="secondary">← Flytt én plass frem</button><button type="button" id="move-later" class="secondary">Flytt én plass bak →</button><span class="muted">I «Mine hyller». Du kan også dra bøkene.</span></div><label class="wide">Notater<textarea name="notes">${esc(b.notes)}</textarea></label></div><div class="form-actions"><span class="muted">Lagres lokalt med endringshistorikk</span><button class="primary" type="submit">Lagre endringer</button></div>
 <div class="asset-list"><h3>Bokfiler <span class="muted">${b.assets.length?'· '+b.assets.length:''}</span></h3>${b.assets.length?b.assets.map(a=>`<div class="asset-row"><a href="/api/file/${a.id}" download>${esc(a.name||b.title)} · ${esc(a.format)} ↗</a><span class="muted">${esc(a.origin)}${a.role==='supplement'?' · Vedlegg':''}${a.narrator?' · '+esc(a.narrator):''}${a.duration_seconds?' · '+Math.floor(a.duration_seconds/3600)+' t '+Math.round(a.duration_seconds%3600/60)+' min':''}</span>${['MP3','M4B','M4A','AAC'].includes(a.format)?`<audio controls preload="none" src="/api/file/${a.id}"></audio>`:''}</div>`).join(''):'<p class="muted">Ingen bokfil lagt til. Leseoppføringen er lagret uavhengig av filen.</p>'}<label class="file-label">Legg til bokfil<input id="book-file" type="file" accept=".epub,.pdf,.mp3,.m4b,.m4a,.aac,.aax,.aaxc"></label><p id="upload-state" class="muted"></p></div><details class="history"><summary>Endringshistorikk</summary><ul id="history-list"></ul></details></form>`;
 $('#move-earlier').onclick=()=>moveBookBy(id,-1);$('#move-later').onclick=()=>moveBookBy(id,1);
 $('#book-form').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),p=Object.fromEntries(f);p.formats=f.getAll('formats');p.read_count=Number(p.read_count||1);p.medium=p.formats.length===1?p.formats[0]:p.formats.length>1?'mixed':'unknown';p.series_index=p.series_index!==''?Number(p.series_index):null;p.year=p.year?Number(p.year):null;p.progress=p.progress!==''?Number(p.progress):null;p.year_uncertain=f.has('year_uncertain');p.title_uncertain=f.has('title_uncertain');let button=e.target.querySelector('[type=submit]');button.disabled=true;try{await api('/api/book/'+id,p);await load();toast('Endringene er lagret');$('#book-dialog').close();}catch(e){toast(e.message);}finally{button.disabled=false;}};
 $('#book-file').onchange=async e=>{let f=e.target.files[0];if(!f)return;$('#upload-state').textContent='Lagrer bokfilen …';e.target.disabled=true;try{let r=await fetch('/api/upload',{method:'POST',headers:{'X-Bokhylla-Token':token,'X-Filename':encodeURIComponent(f.name),'X-Book-Id':id},body:f});let data=await r.json();if(!r.ok)throw Error(data.error);await load();openBook(id);toast('Bokfilen er lagret i arkivet');}catch(e){$('#upload-state').textContent=e.message;$('#book-file').disabled=false;}};
 $('.history').ontoggle=async e=>{if(e.target.open){try{let h=await api('/api/history/'+id);$('#history-list').innerHTML=h.map(x=>`<li>${esc(new Date(x.at).toLocaleString('nb-NO'))} · ${esc(statusNames[x.book.status])} · ${esc(progress(x.book))}</li>`).join('')||'<li>Ingen manuelle endringer ennå.</li>';}catch(e){toast(e.message);}}};
 if(!$('#book-dialog').open)$('#book-dialog').showModal();
}
document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));render();});
document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{format=b.dataset.format;document.querySelectorAll('[data-format]').forEach(x=>x.classList.toggle('active',x===b));render();});
$('#search').oninput=render;$('#sort').onchange=()=>changeArrangement();
$('#export-button').onclick=()=>{let a=document.createElement('a');a.href='/api/export';a.download='bokhylla-'+new Date().toISOString().slice(0,10)+'.json';a.click();};
$('#import-button').onclick=()=>$('#import-dialog').showModal();$('#add-button').onclick=()=>$('#add-dialog').showModal();
$('#add-form').onsubmit=async e=>{e.preventDefault();try{let b=await api('/api/add',Object.fromEntries(new FormData(e.target)));await load();$('#add-dialog').close();e.target.reset();openBook(b.id);}catch(e){toast(e.message);}};
$('#calibre-sync').onclick=async e=>{e.target.disabled=true;try{let r=await api('/api/calibre',{});$('#calibre-result').textContent=`${r.added} nye bøker og ${r.linked} nye filkoblinger. Hoppet over: ${r.skipped.join(', ')}.`;await load();toast('Calibre er oppdatert');}catch(e){toast(e.message);}finally{e.target.disabled=false;}};
$('#audible-file').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let r=await api('/api/audible/preview',{text:await f.text()});audibleRows=r.rows;$('#audible-preview').innerHTML=`<p>${r.rows.length} titler funnet. Lesestatus blir uavklart.</p><ul class="preview-list">${r.rows.map(b=>`<li>${esc(b.title)} — ${esc(b.author)}</li>`).join('')}</ul><button id="confirm-import" class="primary" ${r.rows.length?'':'disabled'}>Importer ${r.rows.length} titler</button>`;$('#confirm-import').onclick=async e=>{e.target.disabled=true;try{let r=await api('/api/audible/import',{rows:audibleRows});await load();$('#audible-preview').textContent=`${r.added} nye bøker lagt til. Eksisterende bøker er beholdt.`;toast('Audible-listen er importert');}catch(err){toast(err.message);e.target.disabled=false;}};}catch(e){$('#audible-preview').textContent=e.message;}};
if(navigator.modelContext){navigator.modelContext.registerTool({name:'search_books',description:'Søk i det lokale biblioteket. Returnerer bok-ID og lesestatus.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query']},execute:async({query})=>({content:[{type:'text',text:JSON.stringify(books.filter(b=>(b.title+' '+b.author).toLowerCase().includes(query.toLowerCase())))}]})});}
// Initial load runs after reading-history.js has installed the history view.

function updateSelectionBar(){
 $('#bulk-bar').hidden=!selectionMode;
 $('#select-mode').textContent=selectionMode?'Avslutt markering':'Marker flere';
 $('#select-mode').setAttribute('aria-pressed',String(selectionMode));
 let hidden=[...selected].filter(id=>!visibleIds.includes(id)).length;
 $('#selection-count').textContent=`${selected.size} valgt${hidden?` · ${hidden} utenfor visningen`:''}`;
 $('#apply-bulk').disabled=bulkBusy||!selected.size||!$('#bulk-status').value;
 $('#apply-bulk').textContent=bulkBusy?'Lagrer …':`Endre status${selected.size?' ('+selected.size+')':''}`;
 $('#select-visible').disabled=bulkBusy||!visibleIds.length;
 $('#clear-selection').disabled=bulkBusy||!selected.size;
 $('#select-mode').disabled=bulkBusy;
 $('#bulk-status').disabled=bulkBusy;
}
$('#select-mode').onclick=()=>{selectionMode=!selectionMode;selected.clear();render();};
$('#select-visible').onclick=()=>{visibleIds.forEach(id=>selected.add(id));render();};
$('#clear-selection').onclick=()=>{selected.clear();render();};
$('#bulk-status').onchange=updateSelectionBar;
$('#bulk-form').onsubmit=async e=>{
 e.preventDefault();if(bulkBusy||!selected.size||!$('#bulk-status').value)return;
 const ids=[...selected],status=$('#bulk-status').value;bulkBusy=true;updateSelectionBar();
 try{
  let r=await api('/api/books/status',{ids,status});
  books.forEach(b=>{if(ids.includes(b.id))b.status=status;});selected.clear();
  toast(`${r.changed} bøker oppdatert til «${statusNames[status]}»`);
  try{await load();}catch(e){toast('Endringene er lagret. Last siden på nytt for å oppdatere visningen.');}
 }catch(e){toast(e.message);}finally{bulkBusy=false;render();}
};

$('#libation-sync').onclick=async e=>{e.target.disabled=true;$('#libation-result').textContent='Leser lydbokmappen …';try{let r=await api('/api/libation',{});$('#libation-result').textContent=`${r.added} nye bokkort, ${r.linked} lydfiler og ${r.pdfs} vedlegg lagt til.${r.errors.length?' '+r.errors.length+' filer kunne ikke leses; prøv igjen når nedlastingen er ferdig.':''}`;await load();toast('Libation-biblioteket er oppdatert');}catch(err){$('#libation-result').textContent=err.message;}finally{e.target.disabled=false;}};
